# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 22:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=128)),
                ('long_description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid postcode.', regex='^([a-zA-Z](([0-9][0-9]?)|([a-zA-Z][0-9][0-9]?)|([a-zA-Z]?[0-9][a-zA-Z])) ?[0-9][abd-hjlnp-uw-zABD-HJLNP-UW-Z]{2})$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Churches',
            },
        ),
    ]
