# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 12:05
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='wide_crop',
            field=image_cropping.fields.ImageRatioField('photo', '768x240', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='wide crop'),
        ),
    ]
