# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0004_auto_20161222_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='classification',
            field=models.CharField(choices=[('T', 'Town'), ('V', 'Village')], default='T', max_length=1),
        ),
    ]
