# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0007_auto_20161222_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name'], 'verbose_name_plural': 'Churches'},
        ),
    ]
