# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0008_auto_20161222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='maps_query',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
