# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0008_auto_20161222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='map_query',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
