# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:00
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0010_auto_20161227_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='list_crop',
            field=image_cropping.fields.ImageRatioField('photo', '500x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='list crop'),
        ),
        migrations.AlterField(
            model_name='church',
            name='wide_crop',
            field=image_cropping.fields.ImageRatioField('photo', '768x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='wide crop'),
        ),
    ]
