# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0012_auto_20161227_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='map_query',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
