# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0013_auto_20170103_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('detail', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('square_crop', image_cropping.fields.ImageRatioField('photo', '64x64', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='square crop')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
