# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0014_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name_plural': 'News'},
        ),
    ]
