# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0016_news_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='detail',
            new_name='text',
        ),
    ]
