# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0017_auto_20170105_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='blurb',
            field=models.CharField(blank=True, help_text='Tweet length (144 characters). Optional.', max_length=144),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
