# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0018_auto_20170107_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_description',
            field=models.CharField(blank=True, help_text='Optional description (useful for screen readers).', max_length=256),
        ),
    ]
