# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0019_auto_20170107_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-datetime',), 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
