# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0021_auto_20170129_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='map_url',
            field=models.URLField(blank=True, default='', editable=False),
        ),
    ]
