# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmanager', '0022_auto_20170129_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='map_embed_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
